// Try catch syntax
try {
    let a;
    console.log(a.length);
    console.log("Hi there from inside");
} catch(err) {
    console.log("Inside catch statement");
}

console.log("hi there");